development:
  adapter: mysql2
  encoding: utf8
  database: signup_development
  username: root
 #password: 
  port: 3306
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: signup_test
  username: root
  # password: 
  port: 3306
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  database: signup_staging
  username: root
  # password: 
  port: 3306
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: signup_production
  username: root
  # password: 
  port: 3306
  host: localhost